'use strict'

function sentenceList (items) {
  return items.map(item => `- ${item}`).join('\n')
}

function escapeCell (value) {
  return String(value || '').replace(/\|/g, '\\|').replace(/\n/g, '<br>')
}

function capabilityPhrase (capability) {
  if (!capability.supported) return 'unsupported'
  const location = capability.location ? ` via ${capability.location}` : ''
  const preposition = capability.strength === 'remediation' && capability.location ? ` after ${capability.location}` : location
  return `${capability.strengthLabel}${preposition}`
}

function renderArchitectureDiagram () {
  return [
    '```mermaid',
    'flowchart LR',
    '  Claude["Claude Code harness"] --> ClaudeAdapter["Claude Adapter"]',
    '  Pi["Pi harness"] --> PiAdapter["Pi Adapter"]',
    '  Future["Future harnesses"] -. capability discovery .-> FutureAdapter["Future Adapter"]',
    '',
    '  ClaudeAdapter --> Normalize["Normalize lifecycle event"]',
    '  PiAdapter --> Normalize',
    '  FutureAdapter -. same boundary .-> Normalize',
    '',
    '  Normalize --> Engine["Workflow Engine"]',
    '  Config["strict .prove_it Project Config"] --> Engine',
    '  Engine --> Shared["Tasks / Pipelines / Signals / State / Evidence / Completion Verification"]',
    '  Shared --> Effects["Harness-neutral Workflow Effects"]',
    '',
    '  Effects --> ClaudeRender["Claude rendering: hook JSON, Stop blocks, backchannel paths"]',
    '  Effects --> PiRender["Pi rendering: extension return values, remediation follow-ups"]',
    '  ClaudeRender --> Claude',
    '  PiRender --> Pi',
    '```'
  ].join('\n')
}

function renderCapabilityMatrix (model) {
  const adapterNames = model.adapters.map(adapter => adapter.displayName)
  const header = ['Capability', ...adapterNames].map(escapeCell).join(' | ')
  const separator = ['---', ...adapterNames.map(() => '---')].join(' | ')
  const capabilityIds = model.adapters[0]?.capabilities.map(capability => capability.id) || []

  const rows = capabilityIds.map(capabilityId => {
    const label = model.adapters[0].capabilities.find(capability => capability.id === capabilityId).label
    const cells = model.adapters.map(adapter => {
      const capability = adapter.capabilities.find(item => item.id === capabilityId)
      return capabilityPhrase(capability)
    })
    return [label, ...cells].map(escapeCell).join(' | ')
  })

  return [`| ${header} |`, `| ${separator} |`, ...rows.map(row => `| ${row} |`)].join('\n')
}

function renderCapabilityDiagnostics (model) {
  const lines = []
  for (const adapter of model.adapters) {
    lines.push(`### ${adapter.displayName}`)
    lines.push('')
    for (const capability of adapter.capabilities) {
      if (!capability.supported) continue
      lines.push(`- **${capability.label}**: ${capabilityPhrase(capability)}`)
      if (capability.diagnostic) lines.push(`  - ${capability.diagnostic}`)
    }
    lines.push('')
  }
  return lines.join('\n').trimEnd()
}

function renderFlow (model) {
  const lines = []
  for (const step of model.flow) {
    lines.push(`### ${step.label}`)
    lines.push('')
    lines.push(step.description)
    lines.push('')
    lines.push(`Examples: ${step.examples.join(', ')}.`)
    lines.push('')
  }
  return lines.join('\n').trimEnd()
}

function renderUnsupportedAdapters (model) {
  if (!model.unsupportedAdapters.length) return 'None.'
  return model.unsupportedAdapters
    .map(adapter => `- **${adapter.displayName}**: ${adapter.status}. ${adapter.note}`)
    .join('\n')
}

function renderArchitectureMarkdown (model) {
  return [
    `# ${model.title}`,
    '',
    '<!-- Generated by `bun tools/visualizer/generate.js`. Do not edit by hand. -->',
    '',
    model.summary,
    '',
    '## Audience',
    '',
    sentenceList(model.primaryAudience),
    '',
    '## Source of truth',
    '',
    'This view is intentionally source-driven. It is generated from repository metadata rather than hand-maintained diagram text.',
    '',
    sentenceList(model.sourceOfTruth),
    '',
    '## Architecture flow',
    '',
    renderArchitectureDiagram(),
    '',
    '## Walkthrough',
    '',
    renderFlow(model),
    '',
    '## Shared Workflow Engine responsibilities',
    '',
    sentenceList(model.sharedResponsibilities),
    '',
    '## Adapter-owned responsibilities',
    '',
    sentenceList(model.adapterResponsibilities),
    '',
    '## Adapter capability matrix',
    '',
    renderCapabilityMatrix(model),
    '',
    '## Capability diagnostics',
    '',
    renderCapabilityDiagnostics(model),
    '',
    '## Not implemented as adapters',
    '',
    renderUnsupportedAdapters(model),
    '',
    '## Design intent',
    '',
    'The architectural boundary is: harnesses are replaceable, adapters are translation layers, and the Workflow Engine owns shared prove_it behavior. Adapter differences are represented as capabilities rather than hidden conditionals in product language.'
  ].join('\n')
}

module.exports = {
  capabilityPhrase,
  renderArchitectureMarkdown
}
